# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_principale_ihm(object):
    def setupUi(self, principale_ihm):
        principale_ihm.setObjectName("principale_ihm")
        principale_ihm.resize(800, 607)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Pictures/IMG_0556.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        principale_ihm.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(principale_ihm)
        self.centralwidget.setObjectName("centralwidget")
        self.conteneur = QtWidgets.QGroupBox(self.centralwidget)
        self.conteneur.setGeometry(QtCore.QRect(50, 20, 491, 391))
        self.conteneur.setObjectName("conteneur")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 420, 481, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bouton_gen = QtWidgets.QPushButton(self.widget)
        self.bouton_gen.setObjectName("bouton_gen")
        self.horizontalLayout.addWidget(self.bouton_gen)
        self.bouton_pas = QtWidgets.QPushButton(self.widget)
        self.bouton_pas.setObjectName("bouton_pas")
        self.horizontalLayout.addWidget(self.bouton_pas)
        self.bouton_sim = QtWidgets.QPushButton(self.widget)
        self.bouton_sim.setObjectName("bouton_sim")
        self.horizontalLayout.addWidget(self.bouton_sim)
        spacerItem = QtWidgets.QSpacerItem(68, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bouton_qui = QtWidgets.QPushButton(self.widget)
        self.bouton_qui.setObjectName("bouton_qui")
        self.horizontalLayout.addWidget(self.bouton_qui)
        principale_ihm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(principale_ihm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menufichier = QtWidgets.QMenu(self.menubar)
        self.menufichier.setToolTipsVisible(False)
        self.menufichier.setObjectName("menufichier")
        principale_ihm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(principale_ihm)
        self.statusbar.setObjectName("statusbar")
        principale_ihm.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(principale_ihm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/coque.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitter.setIcon(icon1)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menufichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menufichier.menuAction())

        self.retranslateUi(principale_ihm)
        self.bouton_qui.clicked.connect(principale_ihm.close) # type: ignore
        self.actionQuitter.triggered.connect(principale_ihm.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(principale_ihm)

    def retranslateUi(self, principale_ihm):
        _translate = QtCore.QCoreApplication.translate
        principale_ihm.setWindowTitle(_translate("principale_ihm", "Ecosysteme"))
        self.conteneur.setTitle(_translate("principale_ihm", "conteneur"))
        self.bouton_gen.setText(_translate("principale_ihm", "Generer"))
        self.bouton_pas.setText(_translate("principale_ihm", "Un pas"))
        self.bouton_sim.setText(_translate("principale_ihm", "Simuler"))
        self.bouton_qui.setText(_translate("principale_ihm", "Quitter"))
        self.menufichier.setTitle(_translate("principale_ihm", "fichier"))
        self.actionQuitter.setText(_translate("principale_ihm", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principale_ihm = QtWidgets.QMainWindow()
    ui = Ui_principale_ihm()
    ui.setupUi(principale_ihm)
    principale_ihm.show()
    sys.exit(app.exec_())
